name       : libupnp
version    : 1.6.22
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.22/libupnp-1.6.22.tar.bz2 : 0bdfacb7fa8d99b78343b550800ff193264f92c66ef67852f87f042fd1a1ebbc
license    : BSD-3 Clause
component  : programming.library
summary    : Portable Open Source UPnP Development Kit
description: |
    The portable Universal Plug and Play (UPnP) SDK provides support for building UPnP-compliant control points, devices, and bridges on Linux.
setup      : |
    %configure --disable-static --enable-ipv6
build      : |
    %make
install    : |
    %make_install
