name       : libupnp
version    : 1.6.20
release    : 2
source     :
    - http://netcologne.dl.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.20/libupnp-1.6.20.tar.bz2 : ee3537081e3ea56f66ada10387486823989210bc98002f098305551c966e3a63
license    : BSD-3 Clause
summary    : Portable Open Source UPnP Development Kit
description: |
    Portable Open Source UPnP Development Kit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
