name       : libupnp
version    : 1.6.24
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.24/libupnp-1.6.24.tar.bz2 : 7d83d79af3bb4062e5c3a58bf2e90d2da5b8b99e2b2d57c23b5b6f766288cf96
license    : BSD-3 Clause
component  : programming.library
summary    : Portable Open Source UPnP Development Kit
description: |
    The portable Universal Plug and Play (UPnP) SDK provides support for building UPnP-compliant control points, devices, and bridges on Linux.
setup      : |
    %configure --disable-static --enable-ipv6
build      : |
    %make
install    : |
    %make_install
