name       : libupnp
version    : 1.6.19
release    : 1
source     :
    - http://netcologne.dl.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.19/libupnp-1.6.19.tar.bz2 : b3142b39601243b50532eec90f4a27dba85eb86f58d4b849ac94edeb29d9b22a
license    : BSD-3 Clause
summary    : Portable Open Source UPnP Development Kit
description: |
    Portable Open Source UPnP Development Kit
builddeps  :
    - glibc-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
