name       : libupnp
version    : 1.6.21
release    : 3
source     :
    - http://netcologne.dl.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.21/libupnp-1.6.21.tar.bz2 : af3f3c0846a1d75baeadae4aa5a2bda427567e2a1fb4559bf73ccff0a4f9a39b
license    : BSD-3 Clause
component  : programming.library
summary    : Portable Open Source UPnP Development Kit
description: |
    Portable Open Source UPnP Development Kit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
