name       : libupnp
version    : 1.14.12
release    : 9
source     :
    - https://github.com/pupnp/pupnp/releases/download/release-1.14.12/libupnp-1.14.12.tar.bz2 : 091c80aada1e939c2294245c122be2f5e337cc932af7f7d40504751680b5b5ac
homepage   : https://pupnp.github.io/pupnp/
license    : BSD-3-Clause
component  : programming.library
summary    : Portable Open Source UPnP Development Kit
description: |
    The portable Universal Plug and Play (UPnP) SDK provides support for building UPnP-compliant control points, devices, and bridges on Linux.
setup      : |
    %configure --disable-static --enable-ipv6
build      : |
    %make
install    : |
    %make_install
